# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
