# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:34
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171024_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_image_directory_path),
        ),
    ]
