# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
