# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171025_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('MATH', 'Math'), ('GUIT', 'Guitar'), ('FOOT', 'Football'), ('SCI', 'Science'), ('BUS', 'Business')], max_length=100),
        ),
    ]
