# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171025_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('MATH', 'Math'), ('GUIT', 'Guitar'), ('FOOT', 'Football'), ('SCI', 'Science'), ('BUS', 'Business')], max_length=100),
        ),
    ]
