# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('VIET', 'Vietnamese'), ('CHI', 'Chinese')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'ENG'), ('MATH', 'MATH'), ('GUIT', 'Guitar'), ('FOOT', 'Football'), ('SCI', 'Science'), ('BUS', 'Business')], max_length=26),
        ),
    ]
