# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171026_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='The skill name', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('VIET', 'Vietnamese'), ('CHI', 'Chinese')], max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('MATH', 'Math'), ('GUIT', 'Guitar'), ('FOOT', 'Football'), ('SCI', 'Science'), ('BUS', 'Business')], max_length=26),
        ),
    ]
