# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171027_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='newskill',
            name='profiles',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
