# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:55
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20171027_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newskill2',
        ),
        migrations.AddField(
            model_name='profile',
            name='newskill2',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='accounts.TagModel'),
        ),
    ]
