# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:10
from __future__ import unicode_literals

from django.db import migrations
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20171027_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newskill2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='newskill',
            field=select2.fields.ManyToManyField(sorted=False, to='accounts.NewSkill'),
        ),
    ]
