# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20171028_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newskill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skillcategory',
            field=models.ManyToManyField(to='accounts.SkillCategory'),
        ),
    ]
