# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20171028_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newskill',
            name='skill_name',
            field=models.CharField(blank=True, help_text='The skill name', max_length=50),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skillcategory',
        ),
        migrations.AddField(
            model_name='profile',
            name='skillcategory',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.SkillCategory'),
        ),
    ]
