# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20171028_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newskill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skillcategory',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='accounts.NewSkill'),
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
