# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:06
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20171029_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ENG', 'English'), ('MATH', 'Math'), ('GUIT', 'Guitar'), ('FOOT', 'Football'), ('SCI', 'Science'), ('BUS', 'Business')], max_length=26),
        ),
    ]
