# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20171029_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='new_skill',
            field=models.ManyToManyField(to='accounts.NewSkill'),
        ),
    ]
