# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20171029_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new_skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='accounts.NewSkill'),
        ),
    ]
